
# App
spring.application.name=notification-service
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:cove1234@cluster0.k2gtlwc.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=notification_db
spring.profiles.active=mongo
# Scheduling
spring.task.scheduling.pool.size=5

# Logging
logging.level.com.patricia.notification=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchanges
rabbitmq.exchange.auth=auth.exchange
rabbitmq.exchange.parche=parche.exchange
rabbitmq.exchange.social=social.exchange

# Queues
rabbitmq.queue.parche-invitation=parche.invitation.queue
rabbitmq.queue.nearby-parche=parche.nearby.queue
rabbitmq.queue.connection-request=social.connection.queue
rabbitmq.queue.otp-verification=auth.otp.verification.queue
rabbitmq.queue.otp-resend=auth.otp.resend.queue
rabbitmq.queue.password-reset=auth.password.reset.queue

# Routing keys
rabbitmq.routing-key.parche-invitation=parche.invitation
rabbitmq.routing-key.nearby-parche=parche.nearby
rabbitmq.routing-key.connection-request=social.connection
rabbitmq.routing-key.otp-verification=auth.otp.verification
rabbitmq.routing-key.otp-resend=auth.otp.resend
rabbitmq.routing-key.password-reset=auth.password.reset

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carreaporfa@gmail.com
spring.mail.password=udwgveabsmzdzgkz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true