# App
spring.application.name=notification-service
server.port=8082

# MongoDB
spring.data.mongodb.uri=mongodb+srv://admin:cove1234@cluster0.k2gtlwc.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=notification_db
spring.profiles.active=mongo
# Scheduling
spring.task.scheduling.pool.size=5

# Logging
logging.level.com.patricia.notification=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true