
# App
spring.application.name=notification-service
server.port=8082

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE:notification_db}
spring.profiles.active=mongo
# Scheduling
spring.task.scheduling.pool.size=5

# Logging
logging.level.com.patricia.notification=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.amqp.rabbit.core.RabbitAdmin=DEBUG

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5671}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL:true}

# Exchanges
rabbitmq.exchange.auth=auth.exchange
rabbitmq.exchange.parche=parche.exchange
rabbitmq.exchange.social=social.exchange

# Queues
rabbitmq.queue.parche-invitation=parche.invitation.queue
rabbitmq.queue.nearby-parche=parche.nearby.queue
rabbitmq.queue.connection-request=social.connection.queue
rabbitmq.queue.otp-verification=auth.otp.verification.queue
rabbitmq.queue.otp-resend=auth.otp.resend.queue
rabbitmq.queue.password-reset=auth.password.reset.queue

# Routing keys
rabbitmq.routing-key.parche-invitation=parche.invitation
rabbitmq.routing-key.nearby-parche=parche.nearby
rabbitmq.routing-key.connection-request=social.connection
rabbitmq.routing-key.otp-verification=auth.otp.verification
rabbitmq.routing-key.otp-resend=auth.otp.resend
rabbitmq.routing-key.password-reset=auth.password.reset

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hangout
rabbitmq.exchange.hangout=hangout.events
rabbitmq.queue.invitation-accepted=hangout.invitation.accepted.queue
rabbitmq.queue.invitation-sent=hangout.invitation.sent.queue
rabbitmq.queue.member-joined=hangout.member.joined.queue
rabbitmq.routing-key.invitation-accepted=invitation.accepted
rabbitmq.routing-key.invitation-sent=invitation.sent
rabbitmq.routing-key.member-joined=member.joined